{
  description = "LBSM Research Environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      supportedSystems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      forAllSystems =
        f: nixpkgs.lib.genAttrs supportedSystems (system: f system);
    in
    {
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs {
            inherit system;
          };
        in
        {
          default = pkgs.mkShell {
            packages = with pkgs; [
              # Python 3.13 stack
              python313
              python313Packages.pip
              python313Packages.numpy
              python313Packages.pandas
              python313Packages.scipy
              python313Packages.scikit-learn
              python313Packages.matplotlib
              python313Packages.seaborn
              python313Packages.jupyterlab
              python313Packages.plotly
              python313Packages.notebook
              python313Packages.ipykernel
              python313Packages.umap-learn
              python313Packages.hmmlearn

              # SageMath is required for project workflows and notebooks.
              sage
            ];

            shellHook = ''
              echo "LBSM research environment ready for system: ${system}"

              # NOTE: heredoc delimiter is intentionally quoted ('EOF', not EOF).
              # An earlier unquoted <<EOF here let bash expand the literal
              # `sage` backticks in the comment below as *command substitution*
              # — since `sage` is a real binary on PATH in this shell, that
              # silently launched an interactive SageMath REPL mid-shellHook,
              # which then hung waiting on the terminal (SIGTTIN/SIGTTOU) and
              # corrupted this file with Sage's banner output. Quoting the
              # delimiter disables all expansion inside the heredoc body, so
              # backticks/`$`/etc. are always inert literal text here.
              cat > requirements.txt <<'EOF'
# Autogenerated from flake.nix
numpy
pandas
scipy
scikit-learn
matplotlib
seaborn
jupyterlab
plotly
notebook
ipykernel
umap-learn
hmmlearn
# NOTE: do not add `sage` here; CI dependency submission validates
# this list against PyPI, and SageMath is provided via Nix/system.
EOF

              echo "✓ requirements.txt synced."
            '';
          };
        });
    };
}