{
  description = "LBSM Research Environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      supportedSystems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      forAllSystems =
        f: nixpkgs.lib.genAttrs supportedSystems (system: f system);
    in
    {
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs {
            inherit system;
          };
        in
        {
          default = pkgs.mkShell {
            packages = with pkgs; [
              # Python 3.13 stack
              python313
              python313Packages.pip
              python313Packages.numpy
              python313Packages.pandas
              python313Packages.scipy
              python313Packages.scikit-learn
              python313Packages.matplotlib
              python313Packages.seaborn
              python313Packages.jupyterlab
              python313Packages.plotly
              python313Packages.notebook
              python313Packages.ipykernel
              python313Packages.umap-learn
              python313Packages.hmmlearn

              # SageMath is required for project workflows and notebooks.
              sage
            ];

            shellHook = ''
              echo "LBSM research environment ready for system: ${system}"

              echo "# Autogenerated from flake.nix" > requirements.txt
              cat >> requirements.txt <<EOF
numpy
pandas
scipy
scikit-learn
matplotlib
seaborn
jupyterlab
plotly
notebook
ipykernel
umap-learn
hmmlearn
# NOTE: do not add `sage` here; CI dependency submission validates
# this list against PyPI, and SageMath is provided via Nix/system.
EOF

              echo "✓ requirements.txt synced."
            '';
          };
        });
    };
}