{
  description = "LBSM Research Environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      # Supported architectures for TMLR reviewers (Linux & macOS)
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      
      # Helper function to generate attributes for each system
      forAllSystems = f: nixpkgs.lib.genAttrs supportedSystems (system: f system);
    in {
      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
        in {
          default = pkgs.mkShell {
            buildInputs = with pkgs; [
              python312
              python312Packages.pip
              python312Packages.numpy
              python312Packages.pandas
              python312Packages.scipy
              python312Packages.scikit-learn
              python312Packages.matplotlib
              python312Packages.seaborn
              python312Packages.jupyterlab
              python312Packages.plotly
              python312Packages.notebook
              python312Packages.ipykernel
              python312Packages.umap-learn
            ];

            shellHook = ''
              echo "LBSM research environment ready for system: ${system}"
              
              # --- Autogenerate requirements.txt fallback ---
              echo "# Autogenerated from flake.nix fallback environment configuration" > requirements.txt
              echo "numpy" >> requirements.txt
              echo "pandas" >> requirements.txt
              echo "scipy" >> requirements.txt
              echo "scikit-learn" >> requirements.txt
              echo "matplotlib" >> requirements.txt
              echo "seaborn" >> requirements.txt
              echo "jupyterlab" >> requirements.txt
              echo "plotly" >> requirements.txt
              echo "notebook" >> requirements.txt
              echo "ipykernel" >> requirements.txt
              echo "umap-learn" >> requirements.txt
              echo "✓ requirements.txt synced with Nix flake packages."
            '';
          };
        });
    };
}
